import { NextResponse } from "next/server";
import { VehicleModel, VehicleColor } from "@/types";

// --- Color Groups ---

const T10X_STANDARD_COLORS: VehicleColor[] = [
  {
    id: "gemlik",
    name: "Gemlik Mavisi",
    localName: "Gemlik",
    hex: "#002D62",
    imageUrl: "/images/t10x/gemlik/gemlik-on-sag.png",
    angles: {
      front: "/images/t10x/gemlik/gemlik-on.png",
      frontLeft: "/images/t10x/gemlik/gemlik-on-sol.png",
      frontRight: "/images/t10x/gemlik/gemlik-on-sag.png",
      side: "/images/t10x/gemlik/gemlik-sol.png",
      rear: "/images/t10x/gemlik/gemlik-arka.png",
      rearLeft: "/images/t10x/gemlik/gemlik-arka-sol.png",
      rearRight: "/images/t10x/gemlik/gemlik-arka-sag.png",
    },
    theme: {
      id: "gemlik",
      name: "Gemlik Mavisi",
      localName: "Gemlik",
      hex: "#002D62",
      bgGradient: "from-[#ffffff] via-[#eff6ff] to-[#f8f9fa]",
      glowColor: "rgba(0, 45, 98, 0.25)",
      borderGlow: "border-blue-500/15",
      shadowGlow: "shadow-blue-950/5 hover:shadow-blue-500/5",
      textHighlight: "text-[#002d62] hover:text-[#001e42]",
      accentHex: "#002D62",
    },
  },
  {
    id: "seyhan",
    name: "Seyhan Gümüşü",
    localName: "Seyhan",
    hex: "#E9ECEF",
    imageUrl: "/images/t10x/seyhan.png",
    theme: {
      id: "seyhan",
      name: "Seyhan Gümüşü",
      localName: "Seyhan",
      hex: "#E9ECEF",
      bgGradient: "from-[#ffffff] via-[#f8fafc] to-[#f8f9fa]",
      glowColor: "rgba(233, 236, 239, 0.2)",
      borderGlow: "border-neutral-500/15",
      shadowGlow: "shadow-neutral-950/5 hover:shadow-neutral-500/5",
      textHighlight: "text-zinc-600 hover:text-zinc-800",
      accentHex: "#E9ECEF",
    },
  },
];

const T10X_OBSIDIAN_COLORS: VehicleColor[] = [
  {
    id: "anadolu",
    name: "Anadolu Kırmızısı",
    localName: "Anadolu",
    hex: "#C51118",
    imageUrl: "/images/t10x/anadolu/anadolu-on-sag.png",
    angles: {
      front: "/images/t10x/anadolu/anadolu-on.png",
      frontLeft: "/images/t10x/anadolu/anadolu-on-sol.png",
      frontRight: "/images/t10x/anadolu/anadolu-on-sag.png",
      side: "/images/t10x/anadolu/anadolu-sol.png",
      rear: "/images/t10x/anadolu/anadolu-arka.png",
      rearLeft: "/images/t10x/anadolu/anadolu-arka-sol.png",
      rearRight: "/images/t10x/anadolu/anadolu-arka-sag.png",
    },
    theme: {
      id: "anadolu",
      name: "Anadolu Kırmızısı",
      localName: "Anadolu",
      hex: "#C51118",
      bgGradient: "from-[#ffffff] via-[#fff5f5] to-[#f8f9fa]",
      glowColor: "rgba(197, 17, 24, 0.25)",
      borderGlow: "border-red-500/15",
      shadowGlow: "shadow-red-950/5 hover:shadow-red-500/5",
      textHighlight: "text-[#c51118] hover:text-[#960a0f]",
      accentHex: "#C51118",
    },
  },
  {
    id: "ayder",
    name: "Ayder Yeşili",
    localName: "Ayder",
    hex: "#004F34",
    imageUrl: "/images/t10x/ayder/ayder-on-sag.png",
    angles: {
      front: "/images/t10x/ayder/ayder-on.png",
      frontLeft: "/images/t10x/ayder/ayder-on-sol.png",
      frontRight: "/images/t10x/ayder/ayder-on-sag.png",
      side: "/images/t10x/ayder/ayder-sol.png",
      rear: "/images/t10x/ayder/ayder-arka.png",
      rearLeft: "/images/t10x/ayder/ayder-arka-sol.png",
      rearRight: "/images/t10x/ayder/ayder-arka-sag.png",
    },
    theme: {
      id: "ayder",
      name: "Ayder Yeşili",
      localName: "Ayder",
      hex: "#004F34",
      bgGradient: "from-[#ffffff] via-[#f0fdf4] to-[#f8f9fa]",
      glowColor: "rgba(0, 79, 52, 0.25)",
      borderGlow: "border-emerald-500/15",
      shadowGlow: "shadow-emerald-950/5 hover:shadow-emerald-500/5",
      textHighlight: "text-[#004f34] hover:text-[#003623]",
      accentHex: "#004F34",
    },
  },
  {
    id: "kapadokya",
    name: "Kapadokya Beji",
    localName: "Kapadokya",
    hex: "#D4A373",
    imageUrl: "/images/t10x/kapadokya/kapadokya-on-sag.png",
    angles: {
      front: "/images/t10x/kapadokya/kapadokya-on.png",
      frontLeft: "/images/t10x/kapadokya/kapadokya-on-sol.png",
      frontRight: "/images/t10x/kapadokya/kapadokya-on-sag.png",
      side: "/images/t10x/kapadokya/kapadokya-sol.png",
      rear: "/images/t10x/kapadokya/kapadokya-arka.png",
      rearLeft: "/images/t10x/kapadokya/kapadokya-arka-sol.png",
      rearRight: "/images/t10x/kapadokya/kapadokya-arka-sag.png",
    },
    theme: {
      id: "kapadokya",
      name: "Kapadokya Beji",
      localName: "Kapadokya",
      hex: "#D4A373",
      bgGradient: "from-[#ffffff] via-[#fdf8f2] to-[#f8f9fa]",
      glowColor: "rgba(212, 163, 115, 0.25)",
      borderGlow: "border-[#d4a373]/15",
      shadowGlow: "shadow-[#d4a373]/5 hover:shadow-[#d4a373]/5",
      textHighlight: "text-[#b88653] hover:text-[#966b3d]",
      accentHex: "#D4A373",
    },
  },
  {
    id: "kula",
    name: "Kula Grisi",
    localName: "Kula",
    hex: "#6C757D",
    imageUrl: "/images/t10x/kula/kula-on-sag.png",
    angles: {
      front: "/images/t10x/kula/kula-on.png",
      frontLeft: "/images/t10x/kula/kula-on-sol.png",
      frontRight: "/images/t10x/kula/kula-on-sag.png",
      side: "/images/t10x/kula/kula-sol.png",
      rear: "/images/t10x/kula/kula-arka.png",
      rearLeft: "/images/t10x/kula/kula-arka-sol.png",
      rearRight: "/images/t10x/kula/kula-arka-sag.png",
    },
    theme: {
      id: "kula",
      name: "Kula Grisi",
      localName: "Kula",
      hex: "#6C757D",
      bgGradient: "from-[#ffffff] via-[#f1f5f9] to-[#f8f9fa]",
      glowColor: "rgba(108, 117, 125, 0.25)",
      borderGlow: "border-slate-500/15",
      shadowGlow: "shadow-slate-950/5 hover:shadow-slate-500/5",
      textHighlight: "text-slate-600 hover:text-slate-800",
      accentHex: "#6C757D",
    },
  },
  {
    id: "oltu",
    name: "Oltu Siyahı",
    localName: "Oltu",
    hex: "#111111",
    imageUrl: "/images/t10x/oltu/oltu-on-sag.png",
    angles: {
      front: "/images/t10x/oltu/oltu-on.png",
      frontLeft: "/images/t10x/oltu/oltu-on-sol.png",
      frontRight: "/images/t10x/oltu/oltu-on-sag.png",
      side: "/images/t10x/oltu/oltu-sol.png",
      rear: "/images/t10x/oltu/oltu-arka.png",
      rearLeft: "/images/t10x/oltu/oltu-arka-sol.png",
      rearRight: "/images/t10x/oltu/oltu-arka-sag.png",
    },
    theme: {
      id: "oltu",
      name: "Oltu Siyahı",
      localName: "Oltu",
      hex: "#111111",
      bgGradient: "from-[#ffffff] via-[#f4f4f5] to-[#f8f9fa]",
      glowColor: "rgba(100, 100, 100, 0.2)",
      borderGlow: "border-zinc-700/15",
      shadowGlow: "shadow-zinc-950/5 hover:shadow-zinc-700/5",
      textHighlight: "text-zinc-700 hover:text-black",
      accentHex: "#222222",
    },
  },
];

const T10F_COLORS: VehicleColor[] = [
  {
    id: "gemlik",
    name: "Gemlik Mavisi",
    localName: "Gemlik",
    hex: "#002D62",
    imageUrl: "/images/t10f/on-sag.png",
    angles: {
      frontLeft: "/images/t10f/on-sol.png",
      frontRight: "/images/t10f/on-sag.png",
      side: "/images/t10f/sol.png",
      rearLeft: "/images/t10f/arka-sol.png",
      rearRight: "/images/t10f/arka-sag.png",
    },
    theme: {
      id: "gemlik",
      name: "Gemlik Mavisi",
      localName: "Gemlik",
      hex: "#002D62",
      bgGradient: "from-[#ffffff] via-[#eff6ff] to-[#f8f9fa]",
      glowColor: "rgba(0, 45, 98, 0.25)",
      borderGlow: "border-blue-500/15",
      shadowGlow: "shadow-blue-950/5 hover:shadow-blue-500/5",
      textHighlight: "text-[#002d62] hover:text-[#001e42]",
      accentHex: "#002D62",
    },
  },
  {
    id: "kula",
    name: "Kula Grisi",
    localName: "Kula",
    hex: "#6C757D",
    imageUrl: "/images/t10f/on-sag.png",
    angles: {
      frontLeft: "/images/t10f/on-sol.png",
      frontRight: "/images/t10f/on-sag.png",
      side: "/images/t10f/sol.png",
      rearLeft: "/images/t10f/arka-sol.png",
      rearRight: "/images/t10f/arka-sag.png",
    },
    theme: {
      id: "kula",
      name: "Kula Grisi",
      localName: "Kula",
      hex: "#6C757D",
      bgGradient: "from-[#ffffff] via-[#f1f5f9] to-[#f8f9fa]",
      glowColor: "rgba(108, 117, 125, 0.25)",
      borderGlow: "border-slate-500/15",
      shadowGlow: "shadow-slate-950/5 hover:shadow-slate-500/5",
      textHighlight: "text-slate-600 hover:text-slate-800",
      accentHex: "#6C757D",
    },
  },
  {
    id: "mardin",
    name: "Mardin Mavisi",
    localName: "Mardin",
    hex: "#8ECAE6",
    imageUrl: "/images/t10f/on-sag.png",
    angles: {
      frontLeft: "/images/t10f/on-sol.png",
      frontRight: "/images/t10f/on-sag.png",
      side: "/images/t10f/sol.png",
      rearLeft: "/images/t10f/arka-sol.png",
      rearRight: "/images/t10f/arka-sag.png",
    },
    theme: {
      id: "mardin",
      name: "Mardin Mavisi",
      localName: "Mardin",
      hex: "#8ECAE6",
      bgGradient: "from-[#ffffff] via-[#f0f9ff] to-[#f8f9fa]",
      glowColor: "rgba(142, 202, 230, 0.25)",
      borderGlow: "border-sky-500/15",
      shadowGlow: "shadow-sky-950/5 hover:shadow-sky-500/5",
      textHighlight: "text-sky-600 hover:text-sky-800",
      accentHex: "#8ECAE6",
    },
  },
  {
    id: "oltu",
    name: "Oltu Siyahı",
    localName: "Oltu",
    hex: "#111111",
    imageUrl: "/images/t10f/on-sag.png",
    angles: {
      frontLeft: "/images/t10f/on-sol.png",
      frontRight: "/images/t10f/on-sag.png",
      side: "/images/t10f/sol.png",
      rearLeft: "/images/t10f/arka-sol.png",
      rearRight: "/images/t10f/arka-sag.png",
    },
    theme: {
      id: "oltu",
      name: "Oltu Siyahı",
      localName: "Oltu",
      hex: "#111111",
      bgGradient: "from-[#ffffff] via-[#f4f4f5] to-[#f8f9fa]",
      glowColor: "rgba(100, 100, 100, 0.2)",
      borderGlow: "border-zinc-700/15",
      shadowGlow: "shadow-zinc-950/5 hover:shadow-zinc-700/5",
      textHighlight: "text-zinc-700 hover:text-black",
      accentHex: "#222222",
    },
  },
  {
    id: "seyhan",
    name: "Seyhan Gümüşü",
    localName: "Seyhan",
    hex: "#E9ECEF",
    imageUrl: "/images/t10f/on-sag.png",
    angles: {
      frontLeft: "/images/t10f/on-sol.png",
      frontRight: "/images/t10f/on-sag.png",
      side: "/images/t10f/sol.png",
      rearLeft: "/images/t10f/arka-sol.png",
      rearRight: "/images/t10f/arka-sag.png",
    },
    theme: {
      id: "seyhan",
      name: "Seyhan Gümüşü",
      localName: "Seyhan",
      hex: "#E9ECEF",
      bgGradient: "from-[#ffffff] via-[#f8fafc] to-[#f8f9fa]",
      glowColor: "rgba(233, 236, 239, 0.2)",
      borderGlow: "border-neutral-500/15",
      shadowGlow: "shadow-neutral-950/5 hover:shadow-neutral-500/5",
      textHighlight: "text-zinc-600 hover:text-zinc-800",
      accentHex: "#E9ECEF",
    },
  },
  {
    id: "urla",
    name: "Urla Turkuazı",
    localName: "Urla",
    hex: "#008080",
    imageUrl: "/images/t10f/on-sag.png",
    angles: {
      frontLeft: "/images/t10f/on-sol.png",
      frontRight: "/images/t10f/on-sag.png",
      side: "/images/t10f/sol.png",
      rearLeft: "/images/t10f/arka-sol.png",
      rearRight: "/images/t10f/arka-sag.png",
    },
    theme: {
      id: "urla",
      name: "Urla Turkuazı",
      localName: "Urla",
      hex: "#008080",
      bgGradient: "from-[#ffffff] via-[#f0fdfa] to-[#f8f9fa]",
      glowColor: "rgba(0, 128, 128, 0.25)",
      borderGlow: "border-teal-500/15",
      shadowGlow: "shadow-teal-950/5 hover:shadow-teal-500/5",
      textHighlight: "text-teal-600 hover:text-teal-800",
      accentHex: "#008080",
    },
  },
];

// --- Vehicle Data ---

const TOGG_VEHICLE_DATA: VehicleModel[] = [
  {
    id: "t10x",
    name: "T10X",
    type: "SUV",
    tagline: "Yeniden Tanımlanan Mobilite Deneyimi",
    description: "Doğu ile Batı'nın, teknoloji ile sanatın buluştuğu premium akıllı cihaz. Yüksek sürüş pozisyonu, geniş iç hacmi ve üstün arazi yetenekleri ile heyecan verici ve sürdürülebilir bir SUV deneyimi.",
    year: "2026",
    trims: [
      {
        id: "v1-rwd-std",
        name: "V1 RWD Standart Menzil",
        priceTry: 1869048,
        deliveryDate: "Eylül 2026",
        specs: {
          rangeWltp: 314,
          batteryCapacity: 52.4,
          fastChargingTime: 28,
          maxPowerKw: 160,
          maxPowerPs: 218,
          maxTorque: 350,
          acceleration: 7.6,
          maxSpeed: 185,
          energyConsumption: 16.9,
        },
        taxDetails: {
          otvRate: 10,
          otvAmount: 186905,
          mtvAmount: 10240,
          registrationFee: 9500,
        },
        colors: T10X_STANDARD_COLORS,
      },
      {
        id: "v1-rwd-long",
        name: "V1 RWD Uzun Menzil",
        priceTry: 2179668,
        deliveryDate: "Ağustos 2026",
        specs: {
          rangeWltp: 523,
          batteryCapacity: 88.5,
          fastChargingTime: 28,
          maxPowerKw: 160,
          maxPowerPs: 218,
          maxTorque: 350,
          acceleration: 7.8,
          maxSpeed: 185,
          energyConsumption: 16.9,
        },
        taxDetails: {
          otvRate: 10,
          otvAmount: 217967,
          mtvAmount: 15800,
          registrationFee: 9500,
        },
        colors: T10X_STANDARD_COLORS,
      },
      {
        id: "v2-rwd-long",
        name: "V2 RWD Uzun Menzil",
        priceTry: 2371000,
        deliveryDate: "Temmuz 2026",
        specs: {
          rangeWltp: 523,
          batteryCapacity: 88.5,
          fastChargingTime: 28,
          maxPowerKw: 160,
          maxPowerPs: 218,
          maxTorque: 350,
          acceleration: 7.8,
          maxSpeed: 185,
          energyConsumption: 16.9,
        },
        taxDetails: {
          otvRate: 10,
          otvAmount: 237100,
          mtvAmount: 15800,
          registrationFee: 9500,
        },
        colors: T10X_STANDARD_COLORS,
      },
      {
        id: "v2-awd-4more",
        name: "V2 AWD 4More Obsidiyen",
        priceTry: 3218057,
        deliveryDate: "Ekim 2026",
        specs: {
          rangeWltp: 485,
          batteryCapacity: 88.5,
          fastChargingTime: 28,
          maxPowerKw: 320,
          maxPowerPs: 435,
          maxTorque: 700,
          acceleration: 4.8,
          maxSpeed: 185,
          energyConsumption: 18.2,
        },
        taxDetails: {
          otvRate: 40,
          otvAmount: 1287223,
          mtvAmount: 31600,
          registrationFee: 9500,
        },
        colors: T10X_OBSIDIAN_COLORS,
      },
    ],
  },
  {
    id: "t10f",
    name: "T10F",
    type: "Sedan",
    tagline: "Zahmetsiz Akışkanlık, Kusursuz Konfor",
    description: "Sıra dışı akıcı Fastback silüeti, aerodinamik mükemmelliği ve yüksek menzilli otonom sürüş asistanlarıyla geleceğin elektrikli sedan standartlarını bugünden belirleyen yenilikçi otomobil.",
    year: "2026",
    trims: [
      {
        id: "t10f-std-rwd",
        name: "V1 RWD Standart Menzil",
        priceTry: 1884980,
        deliveryDate: "Kasım 2026",
        specs: {
          rangeWltp: 350,
          batteryCapacity: 52.4,
          fastChargingTime: 28,
          maxPowerKw: 160,
          maxPowerPs: 218,
          maxTorque: 350,
          acceleration: 7.2,
          maxSpeed: 185,
          energyConsumption: 15.8,
        },
        taxDetails: {
          otvRate: 10,
          otvAmount: 188498,
          mtvAmount: 10240,
          registrationFee: 9500,
        },
        colors: T10F_COLORS,
      },
      {
        id: "t10f-long-rwd-v1",
        name: "V1 RWD Uzun Menzil",
        priceTry: 2195600,
        deliveryDate: "Ekim 2026",
        specs: {
          rangeWltp: 600,
          batteryCapacity: 88.5,
          fastChargingTime: 28,
          maxPowerKw: 160,
          maxPowerPs: 218,
          maxTorque: 350,
          acceleration: 7.4,
          maxSpeed: 185,
          energyConsumption: 15.5,
        },
        taxDetails: {
          otvRate: 10,
          otvAmount: 219560,
          mtvAmount: 15800,
          registrationFee: 9500,
        },
        colors: T10F_COLORS,
      },
      {
        id: "t10f-long-rwd-v2",
        name: "V2 RWD Uzun Menzil",
        priceTry: 2370930,
        deliveryDate: "Kasım 2026",
        specs: {
          rangeWltp: 600,
          batteryCapacity: 88.5,
          fastChargingTime: 28,
          maxPowerKw: 160,
          maxPowerPs: 218,
          maxTorque: 350,
          acceleration: 7.4,
          maxSpeed: 185,
          energyConsumption: 15.5,
        },
        taxDetails: {
          otvRate: 10,
          otvAmount: 237093,
          mtvAmount: 15800,
          registrationFee: 9500,
        },
        colors: T10F_COLORS,
      },
      {
        id: "t10f-long-awd",
        name: "V2 AWD 4More Uzun Menzil",
        priceTry: 3217857,
        deliveryDate: "Aralık 2026",
        specs: {
          rangeWltp: 530,
          batteryCapacity: 88.5,
          fastChargingTime: 28,
          maxPowerKw: 320,
          maxPowerPs: 435,
          maxTorque: 700,
          acceleration: 4.8,
          maxSpeed: 200,
          energyConsumption: 16.6,
        },
        taxDetails: {
          otvRate: 40,
          otvAmount: 1287143,
          mtvAmount: 31600,
          registrationFee: 9500,
        },
        colors: T10F_COLORS,
      },
    ],
  },
];

export async function GET() {
  return NextResponse.json(TOGG_VEHICLE_DATA);
}
export { TOGG_VEHICLE_DATA };
